spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/db23203
    url: jdbc:mariadb://49.161.110.41:3306/DogDB
    #url: jdbc:mariadb://49.161.110.41:3306/test6?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    #username: dbid232
    #password: dbpass232
    username: Dogprj
    password: Dogprj
    #username: dbid231
    #password: dbpass231

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
      #ddl 명령어 :
      #update: 기존의 스키마를 유지하며 JPA에 의해 변경된 부분만 추가한다.
      #validate: 엔티티와 테이블이 정상적으로 매핑되어있는지만 검증한다.
      #create: 기존에 존재하는 스키마를 삭제하고 새로 생성한다.
      #create-drop: 스키마를 생성하고 애플리케이션이 종료될 때 삭제한다.
      #none: 초기화 동작을 하지 않는다.
  mail:
    host: smtp.gmail.com
    port: 587
    username: naxc14@gmail.com
    password: hauxbiwdidnqussq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  resources:static-locations: classpath:/static/


jwt:
  secret:
    key: z$C&F)J@NcRfUjXnZr4u7x!A%D*G-KaP

#server:
  #port: 60003